/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import acciones.TareaAcciones;
import clases.TareaClass;
import java.sql.SQLException;

/**
 *
 * @author Fer
 */
public class CrearTarea extends javax.swing.JFrame {
    
    static void mostrar(){
        CrearTarea crearTarea = new CrearTarea();
        crearTarea.CargarWidget();
        crearTarea.setVisible(true);
        crearTarea.requestFocus();
    }
    TareaNueva tareaNueva;
    /**
     * Creates new form CrearTarea
     */
    private CrearTarea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tareaPanel = new javax.swing.JPanel();
        cancelarButton = new javax.swing.JButton();
        crearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear Tarea");

        tareaPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tareaPanel.setPreferredSize(new java.awt.Dimension(558, 249));
        tareaPanel.setLayout(new javax.swing.BoxLayout(tareaPanel, javax.swing.BoxLayout.Y_AXIS));

        cancelarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_cancel_32px_1.png"))); // NOI18N
        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        crearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_ok_32px_1.png"))); // NOI18N
        crearButton.setText("Crear");
        crearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tareaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(crearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tareaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void crearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearButtonActionPerformed
        TareaClass tareaClass = tareaNueva.getTareaClass();
        try{
            TareaAcciones.guardarTarea(tareaClass);
            tareas.Tareas.principal.agregarTarea(tareaClass);
        } catch (SQLException ex) {
            System.out.print("Error");
        }
        dispose();
    }//GEN-LAST:event_crearButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarButton;
    private javax.swing.JButton crearButton;
    private javax.swing.JPanel tareaPanel;
    // End of variables declaration//GEN-END:variables
    private void CargarWidget(){
        tareaNueva = new TareaNueva();
        tareaNueva.setVisible(true);
        tareaPanel.removeAll();
        tareaPanel.add(tareaNueva);
        validate();
    }
}

